# Generated by Django 3.2.7 on 2021-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='groupes_activites',
            field=models.ManyToManyField(blank=True, related_name='activite_groupes_activites', to='core.TypeGroupeActivite'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveaux',
            field=models.ManyToManyField(related_name='classe_niveaux', to='core.NiveauScolaire'),
        ),
        migrations.AlterField(
            model_name='combitarif',
            name='unites',
            field=models.ManyToManyField(related_name='combi_tarif_unites', to='core.Unite'),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='secteurs',
            field=models.ManyToManyField(blank=True, related_name='ecole_secteurs', to='core.Secteur'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='listes_diffusion',
            field=models.ManyToManyField(blank=True, related_name='individu_listes_diffusion', to='core.ListeDiffusion'),
        ),
        migrations.AlterField(
            model_name='portailperiode',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='periode_categories', to='core.CategorieCompteInternet', verbose_name='Sélection de catégories'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='caisses',
            field=models.ManyToManyField(blank=True, related_name='tarif_caisses', to='core.Caisse', verbose_name='Caisses'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='categories_tarifs',
            field=models.ManyToManyField(related_name='tarif_categories_tarifs', to='core.CategorieTarif', verbose_name='Catégories de tarifs'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='cotisations',
            field=models.ManyToManyField(blank=True, related_name='tarif_cotisations', to='core.TypeCotisation', verbose_name='Cotisations'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='tarif_groupes', to='core.Groupe', verbose_name='Groupes'),
        ),
        migrations.AlterField(
            model_name='uniteremplissage',
            name='unites',
            field=models.ManyToManyField(related_name='unite_remplissage_unites', to='core.Unite', verbose_name='Unités associées'),
        ),
    ]
