# Generated by Django 3.2.9 on 2021-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211111_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='facturation_unite',
            field=models.BooleanField(default=False, help_text='Le montant par unité horaire et la quantité seront mémorisés dans la prestation.', verbose_name='Facturation par unité horaire'),
        ),
    ]
