# Generated by Django 3.2.7 on 2021-09-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210909_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressemail',
            name='structure',
        ),
        migrations.AddField(
            model_name='structure',
            name='adresse_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adressemail', verbose_name='Expéditeur'),
        ),
    ]
