# Generated by Django 3.2.9 on 2021-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211112_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='messagerie_active',
            field=models.BooleanField(default=True, verbose_name='Les familles sont autorisées à converser avec cette structure depuis la rubrique Contact du portail.'),
        ),
    ]
