# Generated by Django 3.2.7 on 2021-09-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210909_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse_exp',
            field=models.ForeignKey(blank=True, help_text="Sélectionnez une adresse d'expédition d'emails favorite dans la liste. Il est possible de créer de nouvelles adresses depuis le menu Paramétrage > Adresses d'expédition.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateur_adresse_exp', to='core.adressemail', verbose_name="Adresse d'expédition d'emails"),
        ),
    ]
