# Generated by Django 3.2.9 on 2021-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_structure_messagerie_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='mandat_structures', to='core.Structure', verbose_name='Structures associées'),
        ),
    ]
