# Generated by Django 3.2.7 on 2021-09-10 09:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_utilisateur_adresse_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFond',
            fields=[
                ('idimage', models.AutoField(db_column='IDimage', primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('image', models.ImageField(upload_to=core.models.get_uuid_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'image de fond',
                'verbose_name_plural': 'images de fond',
                'db_table': 'images_fond',
            },
        ),
    ]
