# Generated by Django 3.2.9 on 2021-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mandat_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitecotisation',
            name='tarifs',
            field=models.TextField(blank=True, null=True, verbose_name='Tarifs'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='structures',
            field=models.ManyToManyField(blank=True, help_text='Ce mandat ne sera utilisé que pour les structures sélectionnées.', related_name='mandat_structures', to='core.Structure', verbose_name='Structures associées'),
        ),
    ]
