# Generated by Django 3.2.9 on 2021-11-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211116_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandat',
            name='sequence',
            field=models.CharField(choices=[('OOFF', 'Prélèvement ponctuel (OOFF)'), ('FRST', "Premier prélèvement d'une série (FRST)"), ('RCUR', "Prélèvement suivant d'une série (RCUR)"), ('FNAL', "Dernier prélèvement d'une série (FNAL)")], default='RCUR', help_text='La prochaine séquence est généralement définie sur RCUR lors de la création du mandat.', max_length=100, verbose_name='Séquence'),
        ),
        migrations.AlterField(
            model_name='pesmodele',
            name='objet_piece',
            field=models.CharField(default='Facture {NUM_FACTURE} - {MOIS_LETTRES} {ANNEE}', help_text="Saisissez l'objet de la pièce par défaut. Vous pouvez personnaliser ce libellé grâce aux mots-clés suivants : {NOM_ORGANISATEUR}, {NUM_FACTURE}, {MOIS}, {MOIS_LETTRES}, {ANNEE}, {DATE_DEBUT_MOIS}, {DATE_FIN_MOIS}.", max_length=450, verbose_name='Libellé de la pièce'),
        ),
        migrations.AlterField(
            model_name='pesmodele',
            name='prelevement_libelle',
            field=models.CharField(default='{NOM_ORGANISATEUR} - Facture {NUM_FACTURE}', help_text='Saisissez le libellé du prélèvement qui apparaîtra sur le relevé de compte de la famille. Vous pouvez personnaliser ce libellé grâce aux mots-clés suivants : {NOM_ORGANISATEUR}, {NUM_FACTURE}, {MOIS}, {MOIS_LETTRES}, {ANNEE}, {DATE_DEBUT_MOIS}, {DATE_FIN_MOIS}.', max_length=450, verbose_name='Libellé du prélèvement'),
        ),
        migrations.AlterField(
            model_name='pesmodele',
            name='prestation_libelle',
            field=models.CharField(default='{INDIVIDU_PRENOM} - {PRESTATION_LABEL}', help_text='Saisissez le libellé de la prestation par défaut. Vous pouvez personnaliser ce libellé grâce aux mots-clés suivants : {ACTIVITE_NOM}, {ACTIVITE_ABREGE}, {PRESTATION_LABEL}, {PRESTATION_QUANTITE}, {PRESTATION_MOIS}, {PRESTATION_ANNEE}, {INDIVIDU_NOM}, {INDIVIDU_PRENOM}, {MOIS}, {MOIS_LETTRES}, {ANNEE}, {DATE_DEBUT_MOIS}, {DATE_FIN_MOIS}.', max_length=450, verbose_name='Libellé de la prestation'),
        ),
        migrations.CreateModel(
            name='SignatureEmail',
            fields=[
                ('idsignature', models.AutoField(db_column='IDsignature', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Texte')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': "signature d'email",
                'verbose_name_plural': "signatures d'emails",
                'db_table': 'signatures_emails',
            },
        ),
    ]
