# Generated by Django 3.2.9 on 2021-11-26 10:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211117_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture'),
        ),
        migrations.AddField(
            model_name='historique',
            name='old',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Ancienne valeur')),
        ),
        migrations.AddField(
            model_name='historique',
            name='portail',
            field=models.BooleanField(default=False, verbose_name='Portail'),
        ),
    ]
