# Generated by Django 3.2.7 on 2021-09-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210913_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='visible_portail',
            field=models.BooleanField(default=True, verbose_name='Visible sur le portail'),
        ),
    ]
