# Generated by Django 3.2.7 on 2021-09-21 18:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_unite_visible_portail'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Mémo'),
        ),
        migrations.AlterField(
            model_name='aide',
            name='jours_scolaires',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'L'), (1, 'M'), (2, 'M'), (3, 'J'), (4, 'V'), (5, 'S'), (6, 'D')], max_length=100, null=True, verbose_name='Jours sur les périodes scolaires'),
        ),
        migrations.AlterField(
            model_name='aide',
            name='jours_vacances',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'L'), (1, 'M'), (2, 'M'), (3, 'J'), (4, 'V'), (5, 'S'), (6, 'D')], max_length=100, null=True, verbose_name='Jours sur les périodes de vacances'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='jours_scolaires',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'L'), (1, 'M'), (2, 'M'), (3, 'J'), (4, 'V'), (5, 'S'), (6, 'D')], max_length=100, null=True, verbose_name='Jours sur les périodes scolaires'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='jours_vacances',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'L'), (1, 'M'), (2, 'M'), (3, 'J'), (4, 'V'), (5, 'S'), (6, 'D')], max_length=100, null=True, verbose_name='Jours sur les périodes de vacances'),
        ),
    ]
