# Generated by Django 3.2.7 on 2021-09-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210921_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='assureur',
            name='cp_resid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='assureur',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Mémo'),
        ),
        migrations.AddField(
            model_name='assureur',
            name='rue_resid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue'),
        ),
        migrations.AddField(
            model_name='assureur',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='assureur',
            name='ville_resid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville'),
        ),
    ]
