# Generated by Django 3.2.9 on 2021-11-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211126_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='portailrenseignement',
            name='rattachement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rattachement', verbose_name='Rattachement'),
        ),
    ]
