# Generated by Django 3.2.7 on 2021-09-25 09:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210921_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemesante',
            name='document',
            field=models.FileField(blank=True, help_text='Vous pouvez ajouter un document.', null=True, upload_to=core.models.get_uuid_path, verbose_name='Document'),
        ),
    ]
