# Generated by Django 3.2.7 on 2021-09-25 09:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_assurance_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotient',
            name='document',
            field=models.FileField(blank=True, help_text='Vous pouvez ajouter un document (PDF ou image).', null=True, upload_to=core.models.get_uuid_path, verbose_name='Document'),
        ),
    ]
