# Generated by Django 3.2.7 on 2021-09-25 22:23

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quotient_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotient',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_uuid_path, verbose_name='Document'),
        ),
        migrations.CreateModel(
            name='PortailDocument',
            fields=[
                ('iddocument', models.AutoField(db_column='IDdocument', primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('texte', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sous-titre')),
                ('couleur_fond', models.CharField(choices=[('primary', 'Bleu foncé'), ('info', 'Bleu clair'), ('success', 'Vert'), ('warning', 'Jaune'), ('danger', 'Rouge'), ('gray', 'Gris')], default='primary', help_text="Couleur de fond de l'icône. Bleu foncé par défaut.", max_length=100, verbose_name='Couleur de fond')),
                ('document', models.FileField(blank=True, help_text='Privilégiez un document au format PDF.', null=True, upload_to=core.models.get_uuid_path, verbose_name='Document')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'portail_documents',
            },
        ),
    ]
