# Generated by Django 3.2.9 on 2021-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_structure_afficher_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='portailperiode',
            name='types_villes',
            field=models.CharField(choices=[('TOUTES', 'Toutes les villes de résidence'), ('SELECTION', 'Uniquement familles résidant sur les villes suivantes'), ('SELECTION_INVERSE', 'Uniquement familles ne résidant pas sur les villes suivantes')], default='TOUTES', max_length=100, verbose_name='Villes'),
        ),
        migrations.AddField(
            model_name='portailperiode',
            name='villes',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Sélection de villes'),
        ),
    ]
