# Generated by Django 3.2.7 on 2021-09-25 22:34

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210925_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaildocument',
            name='document',
            field=models.FileField(help_text='Privilégiez un document au format PDF.', upload_to=core.models.get_uuid_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='portaildocument',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure'),
        ),
    ]
