# Generated by Django 3.2.9 on 2021-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211203_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portailperiode',
            name='types_categories',
            field=models.CharField(choices=[('TOUTES', 'Toutes les catégories de compte internet'), ('AUCUNE', 'Uniquement les catégories de compte internet non renseignées'), ('SELECTION', 'Uniquement les catégories suivantes')], default='TOUTES', max_length=100, verbose_name='Filtre catégories'),
        ),
        migrations.AlterField(
            model_name='portailperiode',
            name='types_villes',
            field=models.CharField(choices=[('TOUTES', 'Toutes les villes de résidence'), ('SELECTION', 'Uniquement les familles résidant sur les villes suivantes'), ('SELECTION_INVERSE', 'Uniquement les familles ne résidant pas sur les villes suivantes')], default='TOUTES', max_length=100, verbose_name='Filtre villes'),
        ),
    ]
