# Generated by Django 3.2.9 on 2021-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211203_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='selection',
            field=models.CharField(choices=[('NON_ENVOYE', "Uniquemement les destinataires qui n'ont pas déjà reçu le message"), ('NON_ENVOYE_10', "Uniquemement les 10 premiers destinataires qui n'ont pas déjà reçu le message"), ('NON_ENVOYE_50', "Uniquemement les 50 premiers destinataires qui n'ont pas déjà reçu le message"), ('NON_ENVOYE_100', "Uniquemement les 100 premiers destinataires qui n'ont pas déjà reçu le message"), ('TOUS', 'Tous les destinataires')], default='NON_ENVOYE', max_length=200, verbose_name='Sélection'),
        ),
    ]
