# Generated by Django 3.2.9 on 2021-12-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleemail',
            name='objet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Objet'),
        ),
    ]
