# Generated by Django 4.0a1 on 2021-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_individu_situation_familiale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='situation_familiale',
            field=models.IntegerField(blank=True, choices=[(1, 'Célibataire'), (2, 'Marié'), (3, 'Divorcé'), (4, 'Veuf'), (5, 'Concubinage'), (6, 'Séparé'), (7, 'Pacsé'), (8, 'Union libre'), (9, 'Autre')], null=True, verbose_name='Situation familiale'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='type_garde',
            field=models.IntegerField(blank=True, choices=[(1, 'Mère'), (2, 'Père'), (3, 'Garde alternée'), (4, 'Autre personne')], null=True, verbose_name='Type de garde'),
        ),
    ]
