# Generated by Django 3.2.8 on 2021-10-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_individu_situation_familiale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='situation_familiale',
            field=models.IntegerField(blank=True, choices=[(1, 'Célibataires'), (2, 'Mariés'), (3, 'Divorcés'), (4, 'Veuf(ve)'), (5, 'En concubinage'), (6, 'Séparés'), (7, 'Pacsés'), (8, 'En union libre'), (9, 'Autre')], null=True, verbose_name='Situation des parents'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='incompatibilites',
            field=models.ManyToManyField(blank=True, related_name='_core_unite_incompatibilites_+', to='core.Unite', verbose_name='Incompatibilités'),
        ),
    ]
