# Generated by Django 3.2.11 on 2022-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='heure_debut_max',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début max.'),
        ),
        migrations.AddField(
            model_name='unite',
            name='heure_debut_min',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début min.'),
        ),
        migrations.AddField(
            model_name='unite',
            name='heure_fin_max',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin max.'),
        ),
        migrations.AddField(
            model_name='unite',
            name='heure_fin_min',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin min.'),
        ),
    ]
