# Generated by Django 3.2.8 on 2021-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20211021_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='annee_deces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de décès'),
        ),
    ]
