# Generated by Django 4.0.2 on 2022-02-08 20:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220201_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='mobile',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='Portable favori')),
        ),
        migrations.AlterField(
            model_name='unite',
            name='incompatibilites',
            field=models.ManyToManyField(blank=True, to='core.Unite', verbose_name='Incompatibilités'),
        ),
    ]
