# Generated by Django 3.2.8 on 2021-10-28 21:46

import core.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20211024_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorieMedicale',
            new_name='CategorieInformation',
        ),
        migrations.AlterModelTable(
            name='categorieinformation',
            table='categories_informations',
        ),
        migrations.AlterModelOptions(
            name='categorieinformation',
            options={'verbose_name': 'catégorie information', 'verbose_name_plural': 'catégories informations'},
        ),
        migrations.DeleteModel(
            name='ProblemeSante',
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('idinformation', models.AutoField(db_column='IDinformation', primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='Intitulé'))),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Description'))),
                ('traitement_medical', models.BooleanField(default=False, verbose_name='Traitement médical')),
                ('description_traitement', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Traitement'))),
                ('date_debut_traitement', models.DateField(blank=True, null=True, verbose_name='Date de début du traitement')),
                ('date_fin_traitement', models.DateField(blank=True, null=True, verbose_name='Date de fin du traitement')),
                ('eviction', models.BooleanField(default=False, verbose_name='Eviction')),
                ('date_debut_eviction', models.DateField(blank=True, null=True, verbose_name="Date de début de l'éviction")),
                ('date_fin_eviction', models.DateField(blank=True, null=True, verbose_name="Date de fin de l'éviction")),
                ('diffusion_listing_enfants', models.BooleanField(default=False, verbose_name='Afficher sur la liste des informations personnelles')),
                ('diffusion_listing_conso', models.BooleanField(default=False, verbose_name='Afficher sur la liste des consommations')),
                ('diffusion_listing_repas', models.BooleanField(default=False, verbose_name='Afficher sur la commande des repas')),
                ('document', models.FileField(blank=True, help_text='Vous pouvez ajouter un document.', null=True, storage=django.core.files.storage.FileSystemStorage, upload_to=core.models.get_uuid_path, verbose_name='Document')),
            ],
            options={
                'verbose_name': 'information',
                'verbose_name_plural': 'informations',
                'db_table': 'informations',
            },
        ),
        migrations.AddField(
            model_name='information',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categorieinformation', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='information',
            name='individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.individu', verbose_name='Individu'),
        ),
    ]
