# Generated by Django 3.2.11 on 2022-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220209_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsms',
            name='nbre_caracteres',
            field=models.IntegerField(default=160, help_text='Précisez le nombre de caractères maximal accepté pour un SMS (160 par défaut).', verbose_name='Nbre caractères max.'),
        ),
    ]
