# Generated by Django 3.2.11 on 2022-03-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220304_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='equiv_heures',
            field=models.TimeField(blank=True, null=True, verbose_name='Equivalence en heures'),
        ),
    ]
