# Generated by Django 3.2.11 on 2022-03-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_unite_equiv_heures'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecotisation',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.activite', verbose_name='Activité'),
        ),
    ]
