# Generated by Django 3.2.11 on 2022-03-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_typecotisation_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='prestation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prestation', verbose_name='Prestation'),
        ),
        migrations.AlterField(
            model_name='typecotisation',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.activite', verbose_name='Activité associée'),
        ),
    ]
