# Generated by Django 3.2.11 on 2022-04-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220409_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perception',
            fields=[
                ('idperception', models.AutoField(db_column='IDperception', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom')),
                ('rue_resid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue')),
                ('cp_resid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code postal')),
                ('ville_resid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'perception',
                'verbose_name_plural': 'perceptions',
                'db_table': 'perceptions',
            },
        ),
        migrations.CreateModel(
            name='PrelevementsModele',
            fields=[
                ('idmodele', models.AutoField(db_column='IDmodele', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('format', models.CharField(choices=[('prive', 'Secteur privé'), ('public_dft', 'Secteur public DFT')], max_length=100, verbose_name='Format')),
                ('reglement_auto', models.BooleanField(default=False, help_text='Cochez cette case si vous souhaitez que Noethysweb créé un règlement automatiquement.', verbose_name='Règlement automatique')),
                ('encodage', models.CharField(choices=[('utf-8', 'UTF-8'), ('iso-8859-15', 'ISO-8859-15')], help_text='Sélectionnez le format souhaité', max_length=100, verbose_name='Encodage')),
                ('identifiant_service', models.TextField(blank=True, help_text="Saisissez l'identifiant du service. Exemple : TGDFT027 (numéro de département sur 3 chiffres).", null=True, verbose_name='Identifiant du service')),
                ('poste_comptable', models.CharField(blank=True, help_text='Saisissez le codique de la DDFiP de rattachement sur 6 caractères. Exemple : 027000', max_length=200, null=True, verbose_name='Poste comptable par défaut')),
                ('compte', models.ForeignKey(help_text='Sélectionnez le compte bancaire à créditer.', on_delete=django.db.models.deletion.PROTECT, to='core.comptebancaire', verbose_name='Compte à créditer')),
                ('mode', models.ForeignKey(blank=True, help_text='Sélectionnez le mode de règlement à utiliser.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modereglement', verbose_name='Mode de règlement')),
                ('perception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.perception', verbose_name='Perception')),
            ],
            options={
                'verbose_name': 'modèle de lot de prélèvements',
                'verbose_name_plural': 'modèles de lot de prélèvements',
                'db_table': 'modeles_prelevements',
            },
        ),
        migrations.CreateModel(
            name='PrelevementsLot',
            fields=[
                ('idlot', models.AutoField(db_column='IDlot', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom interne à l'application. Exemple : Restauration - Janvier 2021.", max_length=200, verbose_name='Nom du lot')),
                ('date', models.DateField(verbose_name='Date de prélèvement')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('motif', models.CharField(blank=True, help_text="Saisissez le motif du prélèvement. Ex : 'Garderie Novembre 2019'.", max_length=300, null=True, verbose_name='Motif')),
                ('numero_sequence', models.IntegerField(blank=True, default=1, help_text='Numéro de séquence du fichier dans une même journée. Exemple: 1 = premier fichier de la journée.', null=True, verbose_name='Numéro de séquence')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.prelevementsmodele', verbose_name='Modèle de lot')),
            ],
            options={
                'verbose_name': 'lot de prélèvements',
                'verbose_name_plural': 'lots de prélèvements',
                'db_table': 'lots_prelevements',
            },
        ),
        migrations.CreateModel(
            name='Prelevements',
            fields=[
                ('idprelevement', models.AutoField(db_column='IDprelevement', primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('facture', 'Facture'), ('manuel', 'Manuel')], default='facture', max_length=100, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('sequence', models.CharField(choices=[('OOFF', 'Prélèvement ponctuel (OOFF)'), ('FRST', "Premier prélèvement d'une série (FRST)"), ('RCUR', "Prélèvement suivant d'une série (RCUR)"), ('FNAL', "Dernier prélèvement d'une série (FNAL)")], max_length=100, verbose_name='Séquence')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('refus', 'Refus'), ('attente', 'Attente')], default='attente', max_length=100, verbose_name='Statut du prélèvement')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.facture', verbose_name='Facture')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.famille', verbose_name='Famille')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.prelevementslot', verbose_name='Lot')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mandat', verbose_name='Mandat')),
            ],
            options={
                'verbose_name': 'prélèvement',
                'verbose_name_plural': 'prélèvements',
                'db_table': 'prelevements',
            },
        ),
    ]
