# Generated by Django 3.2.11 on 2022-10-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20221011_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('idlecture', models.AutoField(db_column='IDlecture', primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='Article')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.famille', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'lecture',
                'verbose_name_plural': 'lectures',
                'db_table': 'lectures',
            },
        ),
    ]
