# Generated by Django 3.2.11 on 2022-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='code_ape',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code APE'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='cp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='mail',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='nom',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='num_agrement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Numéro d'agrément"),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='num_siret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro SIRET'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='rue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site internet'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='tel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville'),
        ),
    ]
