# Generated by Django 3.2.11 on 2022-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20221031_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesmodele',
            name='inclure_tiers_solidaires',
            field=models.BooleanField(default=True, help_text='Cochez cette case si vous souhaitez que Noethys intègre les tiers solidaires.', verbose_name='Inclure les tiers solidaires'),
        ),
    ]
