# Generated by Django 3.2.11 on 2022-11-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20221114_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='tarif_ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tarifligne', verbose_name='Ligne de tarif'),
        ),
    ]
