# Generated by Django 3.2.11 on 2022-11-17 15:13

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20221117_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatairesms',
            name='valeurs',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Valeurs')),
        ),
    ]
