# Generated by Django 3.2.11 on 2022-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_destinatairesms_valeurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='forfait_date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début du forfait'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='forfait_date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin du forfait'),
        ),
    ]
