# Generated by Django 3.2.11 on 2022-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20221119_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='service1',
            field=models.CharField(blank=True, help_text='Premier axe analytique.', max_length=15, null=True, verbose_name='Service axe 1'),
        ),
        migrations.AddField(
            model_name='activite',
            name='service2',
            field=models.CharField(blank=True, help_text='Second axe analytique.', max_length=10, null=True, verbose_name='Service axe 2'),
        ),
    ]
