# Generated by Django 3.2.11 on 2023-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20230103_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(max_length=250, verbose_name='Titre'),
        ),
    ]
