# Generated by Django 3.2.11 on 2023-02-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20230122_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='dependances',
            field=models.ManyToManyField(blank=True, related_name='_core_unite_dependances_+', to='core.Unite', verbose_name='Dépendances'),
        ),
    ]
