# Generated by Django 3.2.11 on 2023-03-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_pespiece_prelevement_reglement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pespiece',
            name='prelevement_reglement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reglement', verbose_name='Règlement'),
        ),
    ]
