# Generated by Django 3.2.11 on 2023-03-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20230305_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifProduit',
            fields=[
                ('idtarif', models.AutoField(db_column='IDtarif', primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('observations', models.CharField(blank=True, max_length=400, null=True, verbose_name='Observations')),
                ('tva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux TVA')),
                ('code_compta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Code comptable')),
                ('methode', models.CharField(choices=[('produit_montant_unique', 'Montant unique'), ('produit_proportionnel_quantite', 'Montant proportionnel à la quantité')], default='montant_unique', max_length=200, verbose_name='Méthode')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Montant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'tarif de produit',
                'verbose_name_plural': 'tarifs de produit',
                'db_table': 'produits_tarifs',
            },
        ),
    ]
