# Generated by Django 3.2.11 on 2023-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20230307_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('cotisation', 'Adhésion'), ('consommation', 'Consommation'), ('location', 'Location'), ('autre', 'Autre')], default='autre', max_length=100, verbose_name='Catégorie'),
        ),
    ]
