# Generated by Django 3.2.11 on 2023-03-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20230314_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptaAnalytique',
            fields=[
                ('idanalytique', models.AutoField(db_column='IDanalytique', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('abrege', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abrégé')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'poste analytique',
                'verbose_name_plural': 'postes analytiques',
                'db_table': 'compta_analytiques',
            },
        ),
        migrations.CreateModel(
            name='ComptaBudget',
            fields=[
                ('idbudget', models.AutoField(db_column='IDbudget', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('analytiques', models.ManyToManyField(related_name='postes_analytiques', to='core.ComptaAnalytique', verbose_name='Poste analytiques')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'db_table': 'compta_budgets',
            },
        ),
        migrations.CreateModel(
            name='ComptaCategorie',
            fields=[
                ('idcategorie', models.AutoField(db_column='IDcategorie', primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=50, verbose_name='Type')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('abrege', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abrégé')),
            ],
            options={
                'verbose_name': 'catégorie comptable',
                'verbose_name_plural': 'catégories comptables',
                'db_table': 'compta_categories',
            },
        ),
        migrations.CreateModel(
            name='ComptaCompteComptable',
            fields=[
                ('idcompte', models.AutoField(db_column='IDcompte', primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'compte comptable',
                'verbose_name_plural': 'comptes comptables',
                'db_table': 'compta_comptes_comptables',
            },
        ),
        migrations.CreateModel(
            name='ComptaOperation',
            fields=[
                ('idoperation', models.AutoField(db_column='IDoperation', primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=50, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date de début')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('num_piece', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro de pièce')),
                ('ref_piece', models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence pièce')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptebancaire', verbose_name='Compte bancaire')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modereglement', verbose_name='Mode de règlement')),
            ],
            options={
                'verbose_name': 'Opération de trésorerie',
                'verbose_name_plural': 'opérations de trésorerie',
                'db_table': 'compta_operations',
            },
        ),
        migrations.CreateModel(
            name='ComptaVentilation',
            fields=[
                ('idventilation', models.AutoField(db_column='IDventilation', primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant')),
                ('date_budget', models.DateField(verbose_name='Date budget')),
                ('analytique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptaanalytique', verbose_name='Analytique')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptacategorie', verbose_name='Catégorie')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptaoperation', verbose_name='Opération')),
            ],
            options={
                'verbose_name': "Ventilation d'une opération",
                'verbose_name_plural': "ventilations d'opérations",
                'db_table': 'compta_ventilation',
            },
        ),
        migrations.CreateModel(
            name='ComptaTiers',
            fields=[
                ('idtiers', models.AutoField(db_column='IDtiers', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'tiers',
                'verbose_name_plural': 'tiers',
                'db_table': 'compta_tiers',
            },
        ),
        migrations.CreateModel(
            name='ComptaReleve',
            fields=[
                ('idreleve', models.AutoField(db_column='IDreleve', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptebancaire', verbose_name='Compte bancaire')),
            ],
            options={
                'verbose_name': 'relevé de compte',
                'verbose_name_plural': 'relevés de compte',
                'db_table': 'compta_releves',
            },
        ),
        migrations.AddField(
            model_name='comptaoperation',
            name='releve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptareleve', verbose_name='Relevé bancaire'),
        ),
        migrations.AddField(
            model_name='comptaoperation',
            name='tiers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptatiers', verbose_name='Tiers'),
        ),
        migrations.CreateModel(
            name='ComptaCategorieBudget',
            fields=[
                ('idcategorie_budget', models.AutoField(db_column='IDcategorie_budget', primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=50, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptabudget', verbose_name='Budget')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptacategorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'catégorie budgétaire',
                'verbose_name_plural': 'catégories budgétaires',
                'db_table': 'compta_categories_budget',
            },
        ),
        migrations.AddField(
            model_name='comptacategorie',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptacomptecomptable', verbose_name='Compte comptable'),
        ),
        migrations.AddField(
            model_name='comptacategorie',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure'),
        ),
    ]
