# Generated by Django 3.2.11 on 2023-03-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20230318_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptavirement',
            name='operation_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virement_operation_credit', to='core.comptaoperation', verbose_name='Opération au crédit'),
        ),
        migrations.AlterField(
            model_name='comptavirement',
            name='operation_debit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virement_operation_debit', to='core.comptaoperation', verbose_name='Opération au débit'),
        ),
    ]
