# Generated by Django 3.2.11 on 2023-03-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20230318_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptaoperation',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modereglement', verbose_name='Mode de règlement'),
        ),
        migrations.AlterField(
            model_name='comptaoperation',
            name='tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptatiers', verbose_name='Tiers'),
        ),
    ]
