# Generated by Django 3.2.11 on 2023-03-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20230318_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptaOperationBudgetaire',
            fields=[
                ('idoperation_budgetaire', models.AutoField(db_column='IDoperation_budgetaire', primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=50, verbose_name='Type')),
                ('date_budget', models.DateField(verbose_name='Date budget')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant')),
                ('analytique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptaanalytique', verbose_name='Analytique')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comptacategorie', verbose_name='Catégorie')),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptebancaire', verbose_name='Compte bancaire')),
            ],
            options={
                'verbose_name': 'opération budgétaire',
                'verbose_name_plural': 'opérations budgétaires',
                'db_table': 'compta_operations_budgetaires',
            },
        ),
    ]
