# Generated by Django 3.2.11 on 2023-03-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaildocument',
            name='type_piece',
            field=models.ForeignKey(blank=True, help_text='Si ce document correspond à un type de pièce existant, sélectionnez-le dans la liste proposée.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typepiece', verbose_name='Type de pièce'),
        ),
    ]
