# Generated by Django 3.2.11 on 2023-03-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_portaildocument_type_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='portail_inscriptions_imposer_pieces',
            field=models.BooleanField(default=False, verbose_name='Imposer le téléchargement des pièces à fournir'),
        ),
        migrations.AlterField(
            model_name='portaildocument',
            name='type_piece',
            field=models.ForeignKey(blank=True, help_text='Si ce document correspond à un type de pièce existant, sélectionnez-le dans la liste proposée.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_piece_document', to='core.typepiece', verbose_name='Type de pièce'),
        ),
    ]
