# Generated by Django 3.2.11 on 2023-03-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20230325_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvenementCollaborateur',
            fields=[
                ('idtype_evenement', models.AutoField(db_column='IDtype_evenement', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type', models.CharField(choices=[('PRESENCE', 'Présence'), ('ABSENCE', 'Absence')], max_length=100, verbose_name='Type')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('couleur', models.CharField(default='#3c8dbc', max_length=100, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': "type d'évènement",
                'verbose_name_plural': "types d'évènements",
                'db_table': 'types_evenements_collaborateur',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collaborateur', verbose_name='Collaborateur'),
        ),
        migrations.CreateModel(
            name='EvenementCollaborateur',
            fields=[
                ('idevenement', models.AutoField(db_column='IDevenement', primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('collaborateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.collaborateur', verbose_name='Collaborateur')),
                ('type_evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typeevenementcollaborateur', verbose_name="Type d'évènement")),
            ],
            options={
                'verbose_name': "évènement d'un collaborateur",
                'verbose_name_plural': "évènements d'un collaborateur",
                'db_table': 'evenements_collaborateur',
            },
        ),
    ]
