# Generated by Django 3.2.11 on 2023-03-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20230326_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelePlanningCollaborateur',
            fields=[
                ('idmodele', models.AutoField(db_column='IDmodele', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('inclure_feries', models.BooleanField(default=False, verbose_name='Inclure les jours fériés')),
            ],
            options={
                'verbose_name': 'modèle de planning',
                'verbose_name_plural': 'modèles de plannings',
                'db_table': 'modeles_planning_collaborateur',
            },
        ),
        migrations.AddField(
            model_name='contratcollaborateur',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
        migrations.CreateModel(
            name='LigneModelePlanningCollaborateur',
            fields=[
                ('idligne', models.AutoField(db_column='IDligne', primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], max_length=50, verbose_name='Jour')),
                ('periode', models.CharField(choices=[('TOUTES', 'Toutes les périodes'), ('SCOLAIRES', 'Période scolaire'), ('VACANCES', 'Période de vacances')], default='TOUTES', max_length=50, verbose_name='Période')),
                ('heure_debut', models.TimeField(verbose_name='Début')),
                ('heure_fin', models.TimeField(verbose_name='Fin')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modeleplanningcollaborateur', verbose_name='Modèle de planning')),
                ('type_evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typeevenementcollaborateur', verbose_name="Type d'évènement")),
            ],
            options={
                'verbose_name': 'ligne de modèle de planning',
                'verbose_name_plural': 'lignes de modèles de planning',
                'db_table': 'lignes_modeles_planning_collaborateur',
            },
        ),
    ]
