# Generated by Django 3.2.11 on 2023-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20230326_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignemodeleplanningcollaborateur',
            name='jour',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour'),
        ),
    ]
