# Generated by Django 3.2.11 on 2023-03-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20230327_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='typepiececollaborateur',
            name='obligatoire',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'None'), ('QUALIFICATIONS', 'Obligatoire pour les qualifications suivantes'), ('POSTES', 'Obligatoire pour les postes suivants')], default='NON', max_length=50, verbose_name='Obligatoire'),
        ),
    ]
