# Generated by Django 3.2.11 on 2023-03-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_typepiececollaborateur_obligatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='equiv_heures',
            field=models.TimeField(blank=True, null=True, verbose_name='Equivalence en heures'),
        ),
        migrations.AlterField(
            model_name='typepiececollaborateur',
            name='obligatoire',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('QUALIFICATIONS', 'Obligatoire pour les qualifications suivantes'), ('POSTES', 'Obligatoire pour les postes suivants')], default='NON', max_length=50, verbose_name='Obligatoire'),
        ),
    ]
