# Generated by Django 3.2.11 on 2023-03-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20230328_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinataire',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collaborateur', verbose_name='Collaborateur'),
        ),
        migrations.AddField(
            model_name='destinatairesms',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collaborateur', verbose_name='Collaborateur'),
        ),
    ]
