# Generated by Django 3.2.11 on 2023-04-03 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20230402_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeCollaborateurs',
            fields=[
                ('idgroupe', models.AutoField(db_column='IDgroupe', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('superviseurs', models.ManyToManyField(related_name='superviseurs_groupe_collaborateurs', to=settings.AUTH_USER_MODEL, verbose_name='Superviseurs')),
            ],
            options={
                'verbose_name': 'groupe de collaborateurs',
                'verbose_name_plural': 'groupes de collaborateurs',
                'db_table': 'groupes_collaborateurs',
            },
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='collaborateur_groupes', to='core.GroupeCollaborateurs', verbose_name='Groupes associés'),
        ),
    ]
