# Generated by Django 3.2.11 on 2023-04-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20230404_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='imposer_saisie_valeur',
            field=models.BooleanField(default=False, verbose_name='Imposer la saisie de la valeur aux usagers sur le portail (uniquement pour les unités de type horaire ou quantité)'),
        ),
        migrations.AlterField(
            model_name='portailperiode',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activite', verbose_name='Activité'),
        ),
    ]
