# Generated by Django 3.2.11 on 2023-04-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20230418_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='prog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transport', verbose_name='Programmation'),
        ),
    ]
