# Generated by Django 3.2.11 on 2023-04-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitecotisation',
            name='prefacturation',
            field=models.BooleanField(default=False, help_text="Cochez cette case pour que la famille puisse payer cette unité d'adhésion sur le portail même si aucune facture n'a été générée.", verbose_name='Activer la préfacturation pour cette unité'),
        ),
    ]
