# Generated by Django 3.2.11 on 2023-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_utilisateur_date_expiration_mdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifligne',
            name='taux',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10, null=True, verbose_name="Taux d'effort"),
        ),
    ]
