# Generated by Django 3.2.11 on 2023-05-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_tarifligne_taux'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleImpression',
            fields=[
                ('idmodele', models.AutoField(db_column='IDmodele', primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('facture', 'Facture'), ('rappel', 'Rappel'), ('attestation_presence', 'Attestation de présence'), ('attestation_fiscale', 'Attestation fiscale'), ('reservations', 'Liste des réservations'), ('cotisation', 'Cotisation'), ('mandat_sepa', 'Mandat SEPA')], max_length=200, verbose_name='Catégorie')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Options')),
                ('defaut', models.BooleanField(default=False, verbose_name='Modèle par défaut')),
                ('modele_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modeledocument', verbose_name='Modèle de document')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': "modèle d'impression",
                'verbose_name_plural': "modèles d'impressions",
                'db_table': 'modeles_impressions',
            },
        ),
    ]
