# Generated by Django 3.2.11 on 2023-05-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20230508_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='portailperiode',
            name='mode_consultation',
            field=models.BooleanField(default=False, help_text='Cochez cette case pour que les familles puissent uniquement consulter les réservations de la période sans pouvoir les modifier.', verbose_name='Mode consultation'),
        ),
    ]
