# Generated by Django 3.2.11 on 2023-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_portailperiode_mode_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='portail_inscriptions_bloquer_si_complet',
            field=models.BooleanField(default=False, verbose_name="Empêcher l'inscription si activité complète"),
        ),
    ]
