# Generated by Django 3.2.11 on 2023-05-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_activite_portail_inscriptions_bloquer_si_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureregie',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptebancaire', verbose_name='Compte bancaire associé'),
        ),
    ]
