# Generated by Django 3.2.21 on 2023-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20230911_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='etat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etat de la facture'),
        ),
    ]
