# Generated by Django 3.2.21 on 2023-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_facture_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='filtre_prestations',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Filtre prestations'),
        ),
    ]
