# Generated by Django 3.2.21 on 2023-09-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date associée'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activite', verbose_name='Activité associée'),
        ),
    ]
