# Generated by Django 3.2.21 on 2023-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_limite_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite paiement en ligne'),
        ),
    ]
