# Generated by Django 3.2.21 on 2023-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_facture_date_limite_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='exclusions_prestations',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Exclusion prestations'),
        ),
    ]
