# Generated by Django 3.2.21 on 2023-10-12 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_alter_tarifligne_montant_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='recu',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='modeleimpression',
            name='categorie',
            field=models.CharField(choices=[('facture', 'Facture'), ('rappel', 'Rappel'), ('attestation_fiscale', 'Attestation fiscale'), ('reglement', 'Reçu de règlement')], max_length=200, verbose_name='Catégorie'),
        ),
    ]
