# Generated by Django 3.2.21 on 2023-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20231012_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifligne',
            name='ajustement',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='Ajustement'),
        ),
    ]
