# Generated by Django 3.2.21 on 2023-11-02 22:23

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsms',
            name='identifiant',
            field=models.CharField(blank=True, help_text="Saisissez l'identifiant de l'utilisateur.", max_length=200, null=True, verbose_name='Identifiant'),
        ),
        migrations.AddField(
            model_name='configurationsms',
            name='motdepasse',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text="Saisissez le mot de passe de l'utilisateur.", max_length=200, null=True, verbose_name='Mot de passe')),
        ),
        migrations.AddField(
            model_name='configurationsms',
            name='nom_compte',
            field=models.CharField(blank=True, help_text='Saisissez le nom du compte.', max_length=200, null=True, verbose_name='Nom du compte'),
        ),
        migrations.AlterField(
            model_name='configurationsms',
            name='moteur',
            field=models.CharField(choices=[('mailjet', 'Mailjet'), ('ovh', 'OVH')], help_text="Sélectionnez un moteur d'expédition.", max_length=200, verbose_name='Moteur'),
        ),
    ]
