# Generated by Django 3.2.21 on 2023-11-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20231102_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='reattribution_adresse_exp',
            field=models.ForeignKey(blank=True, help_text="Sélectionnez l'adresse d'expédition d'emails qui sera utilisée pour envoyer une notification de réattribution de places à la famille.", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.adressemail', verbose_name="Adresse d'expédition"),
        ),
        migrations.AddField(
            model_name='activite',
            name='reattribution_auto',
            field=models.BooleanField(default=False, help_text='Cochez cette case pour laisser Noethysweb réattribuer les places en attente.', verbose_name='Réattribution automatique des places disponibles'),
        ),
        migrations.AddField(
            model_name='activite',
            name='reattribution_delai',
            field=models.IntegerField(blank=True, choices=[(1, '1 jour'), (2, '2 jours'), (3, '3 jours'), (4, '4 jours'), (5, '5 jours'), (7, '1 semaine'), (14, '2 semaines')], default=2, help_text="Sélectionnez le nombre de jours jusqu'auquel il est possible de réattribuer des places.", null=True, verbose_name='Délai de réattribution'),
        ),
    ]
