# Generated by Django 3.2.21 on 2023-11-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20231106_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='reattribution_modele_email',
            field=models.ForeignKey(blank=True, help_text="Sélectionnez le modèle d'email qui sera utilisé pour notifier les familles par email de la réattribution.", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modeleemail', verbose_name="Modèle d'Email"),
        ),
        migrations.AlterField(
            model_name='activite',
            name='reattribution_auto',
            field=models.BooleanField(default=False, help_text='Cochez cette case pour laisser Noethysweb réattribuer les places en attente automatiquement chaque nuit.', verbose_name='Réattribution automatique des places disponibles'),
        ),
    ]
