# Generated by Django 3.2.21 on 2023-11-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20231107_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='visible_fiche_renseignement',
            field=models.BooleanField(default=False, verbose_name='Visible sur les fiches de renseignements'),
        ),
        migrations.AlterField(
            model_name='configurationsms',
            name='moteur',
            field=models.CharField(choices=[('mailjet', 'Mailjet'), ('ovh', 'OVH'), ('brevo', 'Brevo')], help_text="Sélectionnez un moteur d'expédition.", max_length=200, verbose_name='Moteur'),
        ),
    ]
