# Generated by Django 3.2.21 on 2023-12-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20231220_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='email_blocage',
            field=models.BooleanField(default=False, help_text="L'éditeur d'emails groupés du menu Outils ne proposera pas cette famille dans les destinataires.", verbose_name='La famille ne souhaite pas recevoir de mails groupés'),
        ),
        migrations.AddField(
            model_name='famille',
            name='mobile_blocage',
            field=models.BooleanField(default=False, help_text="L'éditeur de SMS groupés du menu Outils ne proposera pas cette famille dans les destinataires.", verbose_name='La famille ne souhaite pas recevoir de SMS groupés'),
        ),
    ]
