# Generated by Django 3.2.21 on 2024-01-07 22:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_auto_20240101_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='code',
            field=models.CharField(default=core.models.get_uuid, max_length=300, verbose_name='Code du sondage'),
        ),
        migrations.AddField(
            model_name='sondage',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Texte après validation'),
        ),
        migrations.AddField(
            model_name='sondage',
            name='modifiable',
            field=models.BooleanField(default=True, verbose_name='Modifiable'),
        ),
        migrations.AddField(
            model_name='sondage',
            name='public',
            field=models.CharField(choices=[('individu', 'Individu'), ('famille', 'Famille')], default='famille', max_length=50, verbose_name='Public'),
        ),
    ]
