# Generated by Django 3.2.21 on 2024-01-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20240107_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondagereponse',
            name='famille',
        ),
        migrations.CreateModel(
            name='SondageRepondant',
            fields=[
                ('idrepondant', models.AutoField(db_column='IDrepondant', primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.famille', verbose_name='Famille')),
                ('individu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.individu', verbose_name='Individu')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sondage', verbose_name='Sondage')),
            ],
            options={
                'verbose_name': 'répondant de sondage',
                'verbose_name_plural': 'répondants de sondages',
                'db_table': 'sondages_repondants',
            },
        ),
        migrations.AddField(
            model_name='sondagereponse',
            name='repondant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sondagerepondant', verbose_name='Répondant'),
        ),
    ]
