# Generated by Django 3.2.21 on 2024-01-13 10:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20240109_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='categories_rattachements',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Représentant'), (2, 'Enfant'), (3, 'Contact')], max_length=200, null=True, verbose_name='Catégories de rattachement'),
        ),
    ]
