# Generated by Django 3.2.23 on 2024-01-15 20:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_sondage_categories_rattachements'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='lienpay',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='categories_rattachements',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Représentant'), (2, 'Enfant'), (3, 'Contact')], help_text="Sélectionnez les catégories d'individus qui pourront être associés à ce sondage.", max_length=200, null=True, verbose_name='Catégories de rattachement'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Ce texte sera affiché après la validation de la réponse par la famille.', null=True, verbose_name='Texte après validation'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='description',
            field=models.TextField(blank=True, help_text='Ce texte sera affiché comme introduction du formulaire de saisie.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='modifiable',
            field=models.BooleanField(default=True, help_text='Cochez cette case si vous souhaitez que les familles puissent modifier leurs réponses.', verbose_name='Réponses modifiables'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='public',
            field=models.CharField(choices=[('individu', 'Individu'), ('famille', 'Famille')], default='famille', help_text='Indiquez si la réponse devra être unique pour la famille ou spécifique à un individu.', max_length=50, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='sondagepage',
            name='description',
            field=models.TextField(blank=True, help_text='Ce texte sera affiché sous le titre de la page.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sondagepage',
            name='titre',
            field=models.CharField(help_text='Ce titre sera affiché uniquement si le sondage comporte plusieurs pages.', max_length=300, verbose_name='Titre'),
        ),
    ]
