# Generated by Django 3.2.23 on 2024-01-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20240115_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='lienpay',
        ),
        migrations.AddField(
            model_name='activite',
            name='pay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
