# Generated by Django 3.2.23 on 2024-01-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20240115_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='pay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
