# Generated by Django 3.2.21 on 2024-02-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20240201_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressemail',
            name='lien_desinscription',
            field=models.BooleanField(default=True, help_text='Un lien de désinscription sera inséré à la fin de chaque mail envoyé par lot.', verbose_name='Insérer un lien de désinscription dans les mails groupés'),
        ),
    ]
