# Generated by Django 3.2.21 on 2024-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_adressemail_lien_desinscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.BigIntegerField(verbose_name='Numéro'),
        ),
    ]
