# Generated by Django 3.2.23 on 2024-01-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_alter_activite_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='pay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
