# Generated by Django 3.2.23 on 2024-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_alter_facture_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='pay',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien paiement direct'),
        ),
        migrations.AddField(
            model_name='activite',
            name='pay_org',
            field=models.BooleanField(default=True, verbose_name='Activation lien paiement'),
        ),
    ]
