# Generated by Django 3.2.23 on 2024-02-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_alter_utilisateur_options'),
        ('core', '0151_auto_20240207_1108'),
    ]

    operations = [
    ]
