# Generated by Django 3.2.21 on 2024-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='visible_portail',
            field=models.BooleanField(default=True, verbose_name='Visible sur le portail'),
        ),
    ]
