# Generated by Django 3.2.21 on 2024-06-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_evenement_visible_portail'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='blocage_impayes_off',
            field=models.BooleanField(default=False, help_text="En cochant cette case, vous permettez à cette famille d'accéder aux réservations du portail même s'il y a des impayés et que le paramètre 'blocage si impayés' a été activé dans les paramètres généraux du portail.", verbose_name='Ne jamais appliquer le blocage des réservations si impayés'),
        ),
    ]
