# Generated by Django 3.2.21 on 2024-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_auto_20240626_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelevements',
            name='libelle',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Libellé'),
        ),
    ]
