# Generated by Django 3.2.21 on 2024-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_prelevements_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressemail',
            name='moteur',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('mailjet', 'Mailjet'), ('brevo', 'Brevo'), ('console', 'Console')], help_text="Sélectionnez un moteur d'expédition (Smtp ou Mailjet).", max_length=200, verbose_name='Moteur'),
        ),
    ]
