# Generated by Django 3.2.21 on 2024-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='forfait_auto',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Automatique'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='forfait_beneficiaire',
            field=models.CharField(blank=True, choices=[('individu', 'Individu'), ('famille', 'Famille')], default='individu', max_length=50, null=True, verbose_name='Bénéficiaire'),
        ),
    ]
