# Generated by Django 5.1.1 on 2024-10-12 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_alter_utilisateur_options_modereglement_code_journal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeModele',
            fields=[
                ('idmodele', models.AutoField(db_column='IDmodele', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('defaut', models.BooleanField(default=False, verbose_name='Modèle par défaut')),
                ('restaurateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.restaurateur', verbose_name='Restaurateur')),
            ],
            options={
                'verbose_name': 'modèle',
                'verbose_name_plural': 'modèles',
                'db_table': 'modeles_commandes',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcommande', models.AutoField(db_column='IDcommande', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(verbose_name='Fin')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.commandemodele', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'db_table': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='CommandeModeleColonne',
            fields=[
                ('idcolonne', models.AutoField(db_column='IDcolonne', primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('largeur', models.IntegerField(default=80, verbose_name='Largeur de la colonne')),
                ('categorie', models.CharField(max_length=200, verbose_name='Catégorie')),
                ('parametres', models.TextField(blank=True, null=True, verbose_name='Paramètres')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commandemodele', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'colonne',
                'verbose_name_plural': 'colonnes',
                'db_table': 'modeles_commandes_colonnes',
            },
        ),
        migrations.CreateModel(
            name='CommandeVersion',
            fields=[
                ('idversion', models.AutoField(db_column='IDversion', primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('valeurs', models.TextField(blank=True, null=True, verbose_name='Valeurs')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'db_table': 'commandes_versions',
            },
        ),
    ]
