# Generated by Django 5.1.1 on 2024-10-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_commandemodele_commande_commandemodelecolonne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemodele',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure'),
        ),
    ]
