# Generated by Django 3.2.21 on 2024-11-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_categorieevenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categorieevenement', verbose_name='Catégorie'),
        ),
    ]
