# Generated by Django 3.2.21 on 2024-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_evenement_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieevenement',
            name='questions',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='categorieevenement',
            name='limitations',
            field=models.CharField(blank=True, choices=[(None, 'Aucune'), ('1EVTSEMAINE', '1 événement par semaine max'), ('2EVTSEMAINE', '2 événements par semaine max'), ('3EVTSEMAINE', '3 événements par semaine max'), ('4EVTSEMAINE', '4 événements par semaine max')], default=None, max_length=100, null=True, verbose_name='Limitation'),
        ),
        migrations.AlterField(
            model_name='questionnairequestion',
            name='categorie',
            field=models.CharField(choices=[('individu', 'Individu'), ('famille', 'Famille'), ('categorie_produit', 'Catégorie de produits'), ('produit', 'Produit'), ('location', 'Location'), ('location_demande', 'Demande de location'), ('inscription', 'Inscription'), ('collaborateur', 'Collaborateur'), ('contrat_collaborateur', 'Contrat collaborateur'), ('consommation', 'Consommation')], max_length=200, verbose_name='Catégorie'),
        ),
    ]
