# Generated by Django 3.2.21 on 2024-11-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20241114_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='Extra'),
        ),
    ]
