# Generated by Django 3.2.21 on 2024-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_consommation_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='obligatoire',
            field=models.BooleanField(default=False, verbose_name='Obligatoire'),
        ),
    ]
