# Generated by Django 3.2.21 on 2024-11-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_questionnairequestion_obligatoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireChoix',
            fields=[
                ('idchoix', models.AutoField(db_column='IDchoix', primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('label', models.CharField(max_length=250, verbose_name='Label')),
                ('couleur', models.CharField(default='#000000', max_length=100, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icône')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionnairequestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'choix de questionnaire',
                'verbose_name_plural': 'choix de questionnaires',
                'db_table': 'questionnaire_choix',
            },
        ),
        migrations.AddField(
            model_name='questionnairereponse',
            name='choix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questionnairechoix', verbose_name='Choix'),
        ),
    ]
