# Generated by Django 3.2.21 on 2024-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20241117_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairechoix',
            name='couleur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='questionnairequestion',
            name='controle',
            field=models.CharField(choices=[('ligne_texte', 'Ligne de texte'), ('bloc_texte', 'Bloc de texte multiligne'), ('entier', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('montant', 'Montant'), ('liste_deroulante', 'Liste déroulante'), ('liste_deroulante_avancee', 'Liste déroulante avancée'), ('liste_coches', 'Sélection multiple'), ('case_coche', 'Case à cocher'), ('date', 'Date'), ('slider', 'Réglette'), ('couleur', 'Couleur'), ('codebarres', 'Code-barres')], max_length=200, verbose_name='contrôle'),
        ),
        migrations.AlterField(
            model_name='sondagequestion',
            name='controle',
            field=models.CharField(choices=[('ligne_texte', 'Ligne de texte'), ('bloc_texte', 'Bloc de texte multiligne'), ('entier', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('montant', 'Montant'), ('liste_deroulante', 'Liste déroulante'), ('liste_deroulante_avancee', 'Liste déroulante avancée'), ('liste_coches', 'Sélection multiple'), ('case_coche', 'Case à cocher'), ('date', 'Date'), ('slider', 'Réglette'), ('couleur', 'Couleur'), ('codebarres', 'Code-barres')], max_length=200, verbose_name='contrôle'),
        ),
    ]
