# Generated by Django 3.2.21 on 2024-11-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20241117_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='couleur',
            field=models.CharField(default='#000000', max_length=100, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='portailchamp',
            name='contact',
            field=models.CharField(choices=[('MASQUER', 'Masqué'), ('AFFICHER', 'Affiché'), ('MODIFIABLE', 'Modifiable'), ('OBLIGATOIRE', 'Obligatoire')], default='MODIFIABLE', max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='portailchamp',
            name='enfant',
            field=models.CharField(choices=[('MASQUER', 'Masqué'), ('AFFICHER', 'Affiché'), ('MODIFIABLE', 'Modifiable'), ('OBLIGATOIRE', 'Obligatoire')], default='MODIFIABLE', max_length=100, verbose_name='Enfant'),
        ),
        migrations.AlterField(
            model_name='portailchamp',
            name='famille',
            field=models.CharField(choices=[('MASQUER', 'Masqué'), ('AFFICHER', 'Affiché'), ('MODIFIABLE', 'Modifiable'), ('OBLIGATOIRE', 'Obligatoire')], default='MODIFIABLE', max_length=100, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='portailchamp',
            name='representant',
            field=models.CharField(choices=[('MASQUER', 'Masqué'), ('AFFICHER', 'Affiché'), ('MODIFIABLE', 'Modifiable'), ('OBLIGATOIRE', 'Obligatoire')], default='MODIFIABLE', max_length=100, verbose_name='Représentant'),
        ),
        migrations.AlterField(
            model_name='questionnairequestion',
            name='controle',
            field=models.CharField(choices=[('ligne_texte', 'Ligne de texte'), ('bloc_texte', 'Bloc de texte multiligne'), ('entier', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('montant', 'Montant'), ('liste_deroulante', 'Liste déroulante basique'), ('liste_deroulante_avancee', 'Liste déroulante avancée'), ('liste_coches', 'Sélection multiple'), ('case_coche', 'Case à cocher'), ('date', 'Date'), ('slider', 'Réglette'), ('couleur', 'Couleur'), ('codebarres', 'Code-barres')], max_length=200, verbose_name='contrôle'),
        ),
        migrations.AlterField(
            model_name='sondagequestion',
            name='controle',
            field=models.CharField(choices=[('ligne_texte', 'Ligne de texte'), ('bloc_texte', 'Bloc de texte multiligne'), ('entier', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('montant', 'Montant'), ('liste_deroulante', 'Liste déroulante basique'), ('liste_deroulante_avancee', 'Liste déroulante avancée'), ('liste_coches', 'Sélection multiple'), ('case_coche', 'Case à cocher'), ('date', 'Date'), ('slider', 'Réglette'), ('couleur', 'Couleur'), ('codebarres', 'Code-barres')], max_length=200, verbose_name='contrôle'),
        ),
    ]
