# Generated by Django 3.2.21 on 2024-11-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20241119_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeleprestation',
            name='multiprestations',
            field=models.TextField(blank=True, null=True, verbose_name='Multi-prestations'),
        ),
        migrations.AlterField(
            model_name='categorieevenement',
            name='limitations',
            field=models.CharField(blank=True, choices=[(None, 'Aucune'), ('1EVTJOUR', '1 événement par jour max'), ('2EVTJOUR', '2 événements par jour max'), ('3EVTJOUR', '3 événements par jour max'), ('1EVTSEMAINE', '1 événement par semaine max'), ('2EVTSEMAINE', '2 événements par semaine max'), ('3EVTSEMAINE', '3 événements par semaine max'), ('4EVTSEMAINE', '4 événements par semaine max')], default=None, max_length=100, null=True, verbose_name='Limitation'),
        ),
    ]
