# Generated by Django 3.2.21 on 2025-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portailperiode',
            name='mode_consultation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation"),
        ),
    ]
