# Generated by Django 3.2.21 on 2025-02-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_portailperiode_mode_consultation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='prestations',
            field=models.TextField(blank=True, null=True, verbose_name='Prestations'),
        ),
    ]
