# Generated by Django 3.2.21 on 2025-02-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_devis_prestations'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='prestations',
            field=models.TextField(blank=True, null=True, verbose_name='Prestations'),
        ),
    ]
