# Generated by Django 3.2.21 on 2025-02-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observations'),
        ),
    ]
