# Generated by Django 3.2.21 on 2025-03-15 12:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_facture_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='pays_naiss_insee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code INSEE pays naissance'),
        ),
        migrations.AddField(
            model_name='individu',
            name='ville_naiss_insee',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='Code INSEE ville naissance')),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='token_api_particulier',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Token API Particulier')),
        ),
    ]
