# Generated by Django 3.2.21 on 2025-03-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_auto_20250315_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='pays_naiss_insee',
            field=models.CharField(blank=True, default='99100', max_length=100, null=True, verbose_name='Code INSEE pays naissance'),
        ),
    ]
