# Generated by Django 5.2.6 on 2025-09-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_alter_utilisateur_options_portailperiode_unites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portailperiode',
            name='unites',
            field=models.ManyToManyField(blank=True, related_name='periode_unites', to='core.unite', verbose_name='Unités à afficher'),
        ),
    ]
