# Generated by Django 5.2.6 on 2025-10-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_alter_portailperiode_unites'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(blank=True, help_text="Saisissez l'URL d'une vidéo. Pour insérer une vidéo Youtube, saisissez l'url 'https://www.youtube.com/embed/xxxxxx' en remplaçant les x par le code youtube de la vidéo.", max_length=300, null=True, verbose_name='Vidéo'),
        ),
    ]
