# Generated by Django 5.2.6 on 2025-10-11 12:01

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_batiment',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Immeuble, bâtiment ou résidence'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_boite',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Boîte postale'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_cp',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_etage',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Etage'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_numero',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numéro de la voie'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_pays',
            field=models.CharField(blank=True, default='FR', max_length=10, null=True, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_rue',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Libellé de la voie'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_service',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identité ou service'),
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='adresse_ville',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='individu_batiment',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Immeuble, bâtiment ou résidence'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='individu_boite',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Boîte postale'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='individu_etage',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Etage'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='individu_numero',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numéro de la voie'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='individu_pays',
            field=models.CharField(blank=True, default='FR', max_length=10, null=True, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='individu_service',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identité ou service'),
        ),
        migrations.AddField(
            model_name='prelevementsmodele',
            name='version_sepa',
            field=models.CharField(choices=[('2009', '2009'), ('2019', '2019')], default='2019', help_text='Sélectionnez la version SEPA souhaitée.', max_length=50, verbose_name='Version SEPA'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='individu_rue',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True, verbose_name='Libellé de la voie')),
        ),
        migrations.AlterField(
            model_name='prelevementsmodele',
            name='encodage',
            field=models.CharField(choices=[('utf-8', 'UTF-8'), ('iso-8859-15', 'ISO-8859-15')], default='utf-8', help_text='Sélectionnez le format souhaité.', max_length=100, verbose_name='Encodage'),
        ),
    ]
