# Generated by Django 5.2.6 on 2025-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_comptebancaire_adresse_batiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perception',
            name='batiment',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Immeuble, bâtiment ou résidence'),
        ),
        migrations.AddField(
            model_name='perception',
            name='boite',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Boîte postale'),
        ),
        migrations.AddField(
            model_name='perception',
            name='etage',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Etage'),
        ),
        migrations.AddField(
            model_name='perception',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numéro de la voie'),
        ),
        migrations.AddField(
            model_name='perception',
            name='pays',
            field=models.CharField(blank=True, default='FR', max_length=10, null=True, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='perception',
            name='service',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identité ou service'),
        ),
        migrations.AlterField(
            model_name='perception',
            name='rue_resid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Libellé de la voie'),
        ),
    ]
