# Generated by Django 5.2.6 on 2026-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='autorisation_apiparticulier',
            field=models.BooleanField(default=True, verbose_name='Autorisation accès API Particulier'),
        ),
    ]
