# Generated by Django 5.2.6 on 2026-09-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_questionnairegroupe_questionnairequestion_groupe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnairegroupe',
            options={'verbose_name': 'regroupement de questions', 'verbose_name_plural': 'regroupements de questions'},
        ),
        migrations.AlterField(
            model_name='questionnairequestion',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questionnairegroupe', verbose_name='Regroupement'),
        ),
    ]
