# Generated by Django 3.2.23 on 2026-03-05 08:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='categories_rattachements',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Adulte'), (2, 'Enfant'), (3, 'Contact')], default=[1, 2, 3], help_text="Sélectionnez les catégories d'individus qui pourront être associés à ce formulaire.", max_length=200, null=True, verbose_name='Catégories de rattachement'),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='public',
            field=models.CharField(choices=[('individu', 'Individu'), ('famille', 'Famille')], default='individu', help_text='Indiquez si la réponse devra être unique pour la famille ou spécifique à un individu.', max_length=50, verbose_name='Public'),
        ),
    ]
