# Generated by Django 3.2.19 on 2026-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date_traitements_visibles',
            field=models.DateTimeField(blank=True, help_text='Saisissez une date pour que les traitements soient visibles sur le portail à partir de cette date. Par défaut, les traitements sont visibles dès leur création.', null=True, verbose_name='Date à partir de laquelle les traitements sont visibles'),
        ),
    ]
