# Generated by Django 3.2.23 on 2026-03-05 09:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_alter_sondage_categories_rattachements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='categories_rattachements',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Adulte'), (2, 'Enfant'), (3, 'Contact')], default='2', help_text="Sélectionnez les catégories d'individus qui pourront être associés à ce formulaire.", max_length=200, null=True, verbose_name='Catégories de rattachement'),
        ),
    ]
