# Generated by Django 3.2.19 on 2026-03-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0235_activite_date_traitements_visibles'),
        ('core', '0237_alter_sondage_categories_rattachements'),
    ]

    operations = [
    ]
