# Generated by Django 3.2.23 on 2026-03-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure'),
        ),
    ]
